### ISSUE TITLE
Uninstall homeeup

### ISSUE THREAD

**Issue by SteffenTM** [kdietrich/homeeup#16]
Hello, i run a homee system with a hardware CCU2. As i read the real CCU and the homeeup-CCU not working well together. I have this issue as well. So i want to uninstall the homeeup from my raspberry. The normal way with command "sudo apt-get purge homeeup" is not working. May someone can give me an advise.

Thanx, Steffen

**Comment by kdietrich** [comment]
Hello Steffen,

have you tried `sudo npm uninstall homeeup`?

Best,
Kevin

**Comment by SteffenTM** [comment]
Hello Kevin,

i just tried it out. I got this back:

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

up to date in 2.162s
found 0 vulnerabilities

May you have an idea.

Regards,
Steffen

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Kevin Dietrich <notifications@github.com>
Gesendet: Tuesday, June 18, 2019 11:20:53 AM
An: kdietrich/homeeup
Cc: SteffenTM; Author
Betreff: Re: [kdietrich/homeeup] Uninstall homeeup (#16)


Hello Steffen,

have you tried sudo npm uninstall homeeup?

Best,
Kevin
