### ISSUE TITLE
Can you please provide example configs for the not-yet-documented Plugins?

### ISSUE THREAD

**Issue by hblaschka** [kdietrich/homeeup#7]
Kevin,

could you please provide example config entries for the not-yet-documented Plugins (FritzBox & MQTT) on the Readme?

A Wiki-Entry on homeepedia.de (https://www.homeepedia.de/books/homeean/page/homeeup/) about homeeup is on my ToDo-List and Work in Progress and I want to make sure I describe everything correctly for the target group of homeean. Thanx

**Comment by kdietrich** [comment]
Plugins are/will be documented here: https://github.com/kdietrich/homeeup#plugins
